#	$NetBSD: Makefile,v 1.8 2015/01/05 22:15:19 showell Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

NOMAN=	# defined

PROG=	announce

CFLAGS += -DIDENT=\""${CUSTOM_IDENTIFIER}"\"

.include <bsd.prog.mk>
